### ISSUE TITLE
Routing to next page doesn't work in Flutter web

### ISSUE THREAD

**Issue by thetnswe** [jonataslaw/get#224]
Get.offAllNamed(routeName);
Get.offNamed(routeName); 
Get.toNamed(routeName);

These three doesn't work with Flutter web.

**To Reproduce**
1. Create a new flutter web project
2. Call any of the above function to show the new page
3. Only blank screen renders on web page

4. Error
stack_trace_mapper.js:265 Uncaught Bad state: Source maps are not done loading.
    at Object.a (http://localhost:59816/stack_trace_mapper.js:265:3)
    at cA.kf (http://localhost:59816/stack_trace_mapper.js:2722:23)
    at Object.iM (http://localhost:59816/stack_trace_mapper.js:220:69)
    at jz (http://localhost:59816/stack_trace_mapper.js:2442:10)
    at http://localhost:59816/stack_trace_mapper.js:2436:42
    at dart._StackTrace.new.toString (http://localhost:59816/dart_sdk.js:7062:19)
    at Object._toString [as toString] (http://localhost:59816/dart_sdk.js:4889:26)
    at new assertions.DiagnosticsStackTrace.new (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3527:212)
    at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3258:24)
    at http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:2362:38
    at assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:2365:28)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3541:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:2377:54)
    at diagnostics$.TextTreeRenderer.new.[_debugRender] (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:1184:37)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:1098:34)
    at Function.dumpErrorToConsole (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3364:142)
    at Function.<anonymous> (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3498:57)
    at Function.reportError (http://localhost:59816/packages/flutter/src/foundation/debug.dart.js:3460:76)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:59816/packages/flutter/src/scheduler/binding.dart.js:730:33)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:59816/packages/flutter/src/scheduler/binding.dart.js:698:37)
    at http://localhost:59816/packages/flutter/src/scheduler/binding.dart.js:616:14
    at internalCallback (http://localhost:59816/dart_sdk.js:23470:11)

**Comment by jonataslaw** [comment]
This is not a Get error.
All functions mentioned work as intended.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/',
      namedRoutes: {
        '/': GetRoute(page: Home()),
        '/second': GetRoute(page: Second()),
        '/third': GetRoute(page: Third())
      },
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.toNamed('/second');
          },
          child: Text('go to second')),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.offNamed('/third');
          },
          child: Text('go to third')),
    );
  }
}

class Third extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.offAllNamed('/');
          },
          child: Text('offall to home')),
    );
  }
}
```

**Comment by thetnswe** [comment]
Oh! Thanks alot for the clarification. I was just using routes in the
GetMaterialApp and didn't use namedRoutes that Get is provided. Will try
again.

With Best Regards,
Thet Naing Swe
Founder & Chief Technical Officer
Twitter: @thetnswe

Company info:
URL: http://joydash.com
Twitter : @JoyDashGames <http://twitter.com/JoyDashGames>
Fan page: http://www.facebook.com/JoyDashGames
